[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "/tags/"
  weight = 40
